# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e61b0c5ca1e4e3422229500ecf18e0c1c7857a5431760c290e19e1e2953be1954914c34af3c0de7b80422ba7bcab1959ba51bd3ce95c595ea63be2bd147361c5

test:
  secret_key_base: dfdefddb30e328e4f022b8896477a4168649608337d831d4c5b61910510c027c218c7fec8545b7e4447f8ab9627e4160e1b8d5cf09078b5db10ec86372c40be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
